"""Identifier sites and the license decision (I662-S4c, S4d): every live id site is accounted for, and color-scheme license stays free text."""
from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any, Iterator

import pytest
import yaml

from chrona.resources import SCHEMA_PARTS, schema_document, validator_for_schema
from tools.schema_inventory import load_inventory


ROOT = next(parent for parent in Path(__file__).resolve().parents if (parent / "pyproject.toml").is_file())
SCHEMAS = ROOT / "schemas"
COMMON_ID = "urn:chrona:common-v0.1"
ENTRIES = load_inventory(SCHEMAS / "schema-inventory-v0.1.yaml")
LIVE = tuple(entry["file"] for entry in ENTRIES if entry["state"] == "live")
PARTS = frozenset(SCHEMA_PARTS)


def _schema(name: str) -> dict[str, Any]:
    return yaml.safe_load((SCHEMAS / name).read_bytes())


def _walk(node: Any) -> Iterator[Any]:
    yield node
    if isinstance(node, dict):
        for value in node.values():
            yield from _walk(value)
    elif isinstance(node, list):
        for value in node:
            yield from _walk(value)


# --------------------------------------------------------------------------------------------
# S4c: the id-site inventory (B5). Existing ids are NOT tightened; each site is classified and counted.
# --------------------------------------------------------------------------------------------

# category -> why a site of that shape does not reference `common#identifier`.
ALLOWED_SHAPES: dict[str, str] = {
    "non-empty-string": "an authored identifier that has only ever been `minLength: 1`: committed and user documents use spaces, punctuation and non-ASCII, "
                        "and `identifier` also refuses control characters, so referencing it would newly reject an input (N1, B5 not unified)",
    "unconstrained-string": "Project relation ids have no length rule at all; tightening even to non-empty changes what Project accepts",
    "bounded-non-empty-string": "review-detail-profile ids carry their own 4096 bound, a different contract from `identifier`",
    "figure-identity": "View figure ids share one View-local definition with the historical non-empty-string grammar, without changing typed-ingress validation",
    "layout-profile-id": "layout-profile declares its own stricter `id` (`^[A-Za-z][A-Za-z0-9._-]*$`, bounded); it is a named local definition, not a copy",
    "slug": "a lowercase catalogue key (`slug`), a different concept from a free identifier",
    "portable-name": "a portable asset or set name (`portableName`), a different concept from a free identifier",
    "store-segment": "the registry baseline name (`snapshotId`) is stored as `snapshots/<id>.yaml`, so it is one `storeAddress` segment (#710), "
                     "stricter than `identifier` on purpose: no separator, drive, backslash, control or non-ASCII character",
    "scene-text": "Scene ids are generated by Layout and serialised, never authored; Scene types them as text",
}

# (file, category) -> number of id-valued properties (the name is `id` or ends in `Id`).
ID_SITES: dict[tuple[str, str], int] = {
    ("actual-intake-batch-v0.2.schema.yaml", "non-empty-string"): 2,
    ("actual-set-v0.3.schema.yaml", "non-empty-string"): 3,
    ("authoring-command-result-v0.1.schema.yaml", "non-empty-string"): 1,
    ("authoring-command-v0.1.schema.yaml", "non-empty-string"): 4,
    ("authoring-workspace-v0.1.schema.yaml", "non-empty-string"): 8,
    ("color-scheme-v0.2.schema.yaml", "non-empty-string"): 1,
    ("command-request-v0.3.schema.yaml", "non-empty-string"): 6,
    ("command-request-v0.3.schema.yaml", "store-segment"): 1,
    ("example-registry-v0.1.schema.yaml", "slug"): 1,
    ("layout-profile-v0.10.schema.yaml", "layout-profile-id"): 7,
    ("presentation-materialization-receipt-v0.1.schema.yaml", "non-empty-string"): 1,
    ("presentation-preset-v0.1.schema.yaml", "non-empty-string"): 4,
    ("preset-library-v0.2.schema.yaml", "non-empty-string"): 5,
    ("preset-library-v0.2.schema.yaml", "portable-name"): 1,
    ("preset-library-v0.2.schema.yaml", "slug"): 1,
    ("profile-v0.3.schema.yaml", "non-empty-string"): 1,
    ("project-v0.7.schema.yaml", "non-empty-string"): 3,
    ("project-v0.7.schema.yaml", "unconstrained-string"): 1,
    ("render-context-v0.17.schema.yaml", "non-empty-string"): 2,
    ("review-detail-profile-v0.1.schema.yaml", "bounded-non-empty-string"): 4,
    # R6 adds Layout-generated target-port and terminal-owner identities, not authored IDs.
    ("scene-v0.7.schema.yaml", "scene-text"): 31,
    ("snapshot-ref-v0.3.schema.yaml", "non-empty-string"): 1,
    ("summary-profile-v0.2.schema.yaml", "non-empty-string"): 3,
    ("theme-asset-source-v0.2.schema.yaml", "portable-name"): 1,
    ("theme-v0.15.schema.yaml", "non-empty-string"): 1,
    ("theme-v0.16.schema.yaml", "non-empty-string"): 2,
    ("view-v0.28.schema.yaml", "figure-identity"): 3,
    ("view-v0.28.schema.yaml", "non-empty-string"): 17,
}


def _category(node: dict[str, Any]) -> str:
    shape = {key: value for key, value in node.items() if key not in {"description", "examples"}}
    if shape == {"$ref": f"{COMMON_ID}#/$defs/identifier"}:
        return "identifier"
    if shape == {"type": "string", "minLength": 1}:
        return "non-empty-string"
    if shape == {"type": "string"}:
        return "unconstrained-string"
    if shape == {"type": "string", "minLength": 1, "maxLength": 4096}:
        return "bounded-non-empty-string"
    if shape == {"$ref": "#/$defs/id"}:
        return "layout-profile-id"
    if shape == {"$ref": "#/$defs/figureIdentity"}:
        return "figure-identity"
    if shape == {"$ref": f"{COMMON_ID}#/$defs/slug"}:
        return "slug"
    if shape in ({"$ref": f"{COMMON_ID}#/$defs/portableName"}, {"$ref": "#/$defs/name"}):
        return "portable-name"
    if shape == {"$ref": f"{COMMON_ID}#/$defs/storeAddress", "pattern": "^[^/]+$"}:
        return "store-segment"
    if shape in ({"$ref": "#/$defs/string"}, {"$ref": "#/$defs/text"}):
        return "scene-text"
    return "UNCLASSIFIED"


def _id_sites(name: str) -> list[tuple[str, str]]:
    return [(key, _category(value)) for node in _walk(_schema(name))
            if isinstance(node, dict) and isinstance(node.get("properties"), dict)
            for key, value in node["properties"].items() if key == "id" or key.endswith("Id")]


def _all_sites() -> Counter[tuple[str, str]]:
    counts: Counter[tuple[str, str]] = Counter()
    for name in LIVE:
        if name not in PARTS:
            counts.update((name, category) for _, category in _id_sites(name))
    return counts


def test_every_live_id_site_references_identifier_or_is_on_the_documented_allowlist():
    counts = _all_sites()
    assert not [key for key in counts if key[1] == "UNCLASSIFIED"], sorted(key for key in counts if key[1] == "UNCLASSIFIED")
    unaccounted = {key: n for key, n in counts.items() if key[1] != "identifier" and key not in ID_SITES}
    assert unaccounted == {}, "a new id site needs a category or a reference to `identifier`"
    assert {key: n for key, n in counts.items() if key[1] != "identifier"} == ID_SITES


def test_every_allowlisted_category_has_a_recorded_reason_and_no_entry_is_stale():
    assert {category for _, category in ID_SITES} <= set(ALLOWED_SHAPES)
    assert set(ALLOWED_SHAPES) == {category for _, category in ID_SITES}, "a reason without a site is stale"
    assert all(len(reason) > 40 for reason in ALLOWED_SHAPES.values())


def test_scene_fan_in_uses_the_existing_opaque_generated_identity_contract():
    fan_in = _schema("scene-v0.7.schema.yaml")["$defs"]["relationFanIn"]
    assert fan_in["required"] == ["targetPortId", "terminalOwnerId"]
    assert fan_in["properties"] == {
        "targetPortId": {"$ref": "#/$defs/string"},
        "terminalOwnerId": {"$ref": "#/$defs/string"},
    }


def test_the_resource_envelope_id_of_a_part_consumer_is_the_part_not_an_inline_copy():
    # View, both icon catalogs and summary-profile take `id` from presentation-resource; they declare no inline envelope id.
    part = schema_document("presentation-resource-v0.1.schema.yaml")["$defs"]
    assert "resourceRef" in part
    for name in ("view-v0.28.schema.yaml", "icon-catalog-v0.5.schema.yaml", "summary-profile-v0.2.schema.yaml"):
        assert "urn:chrona:presentation-resource-v0.1" in (SCHEMAS / name).read_text(encoding="utf-8")


def test_identifier_is_defined_but_no_existing_id_is_tightened_to_it():
    # N1: `identifier` exists for new ids. It refuses empty strings and control characters and accepts everything else an
    # authored id uses today, so a site can adopt it at its next bump with only control-character inputs newly refused.
    validator = validator_for_schema({"$ref": f"{COMMON_ID}#/$defs/identifier"})
    today = validator_for_schema({"type": "string", "minLength": 1})
    everyday = ["x", "Work package / gate", "作業ストリーム", "Δ", "#", "supplier:FW-42", " padded ", "a b", "a.b_c-d"]
    assert [value for value in everyday if not validator.is_valid(value) or not today.is_valid(value)] == []
    control = ["a\nb", "a\tb", "\x00", "a\x7f", "a\n"]
    assert [value for value in control if not today.is_valid(value)] == [], "today's ids accept control characters"
    assert [value for value in control if validator.is_valid(value)] == [], "identifier refuses them"
    assert all(category != "identifier" for _, category in _all_sites()), "no site adopts identifier yet: adopting is a tightening"


def test_view_figure_kinds_share_one_local_identity_definition():
    view = _schema("view-v0.28.schema.yaml")["$defs"]
    identity = view["figureIdentity"]
    assert {key: value for key, value in identity.items() if key not in {"description", "examples"}} == {
        "type": "string", "minLength": 1,
    }
    for kind in ("figureDaysUntil", "figureDaysIn", "figureCount"):
        assert view[kind]["properties"]["id"]["$ref"] == "#/$defs/figureIdentity"


# --------------------------------------------------------------------------------------------
# S4d: license (B7). The asset schemas share `license`; color-scheme stays free text.
# --------------------------------------------------------------------------------------------

COLOR_SCHEME = "color-scheme-v0.2.schema.yaml"


def _scheme(license_value: Any) -> dict[str, Any]:
    document = yaml.safe_load((ROOT / "examples/aster-ssd/schemes/executive-light.yaml").read_bytes())
    document["body"]["provenance"]["license"] = license_value
    return document


@pytest.mark.parametrize("value", ["project-pending", "MIT", "CC-BY-4.0, attribution required", "Apache-2.0 WITH LLVM-exception", " free text "])
def test_color_scheme_license_stays_free_text(value):
    assert validator_for_schema(_schema(COLOR_SCHEME)).is_valid(_scheme(value))


@pytest.mark.parametrize("value", ["", 5, None, {"spdx": "MIT", "notice": "n"}, ["MIT"]])
def test_color_scheme_license_is_still_a_non_empty_string(value):
    assert not validator_for_schema(_schema(COLOR_SCHEME)).is_valid(_scheme(value))


def test_committed_schemes_keep_their_project_pending_license():
    declared = {path: yaml.safe_load(path.read_bytes())["body"]["provenance"]["license"]
                for path in sorted((ROOT / "examples").glob("*/schemes/*.yaml"))}
    assert "project-pending" in declared.values()
    validator = validator_for_schema(_schema(COLOR_SCHEME))
    for path in declared:
        assert validator.is_valid(yaml.safe_load(path.read_bytes())), path


def test_the_asset_schemas_share_the_license_object_and_color_scheme_does_not():
    assert COMMON_ID + "#/$defs/license" in (SCHEMAS / "icon-catalog-v0.5.schema.yaml").read_text(encoding="utf-8")
    assert COMMON_ID + "#/$defs/license" in (SCHEMAS / "theme-asset-source-v0.2.schema.yaml").read_text(encoding="utf-8")
    assert "common-v0.1#/$defs/license" not in (SCHEMAS / COLOR_SCHEME).read_text(encoding="utf-8")
    license_field = next(node["properties"]["license"] for node in _walk(_schema(COLOR_SCHEME))
                         if isinstance(node, dict) and isinstance(node.get("properties"), dict) and "license" in node["properties"])
    assert license_field["type"] == "string" and license_field["minLength"] == 1
    assert "free text" in license_field["description"]
