"""Golden pairs: compiler output equals the committed bytes, the expected Project validates and schedules the same (#148)."""
from __future__ import annotations

import pytest

from chrona.core.validation import validate_project
from tests.support.terse_plans import FIXTURES, compile_fixture, edges, load_yaml_bytes, schedule_summary

PLANS = sorted(path.stem for path in FIXTURES.glob("*.chrona"))


def test_every_plan_has_a_golden_twin_and_nothing_else_is_stale():
    expected = {path.name.removesuffix(".project.yaml") for path in FIXTURES.glob("*.project.yaml")}
    assert expected == set(PLANS)
    assert {"minimal-starter", "issue-sketch", "halcyon-1-core", "groups", "anchors-bounds", "calendars",
            "forward-references", "yaml-hazard-names", "special-characters"} <= set(PLANS)


@pytest.mark.parametrize("plan", PLANS)
def test_output_bytes_equal_the_committed_golden(plan):
    compiled = compile_fixture(f"{plan}.chrona")
    assert compiled.ok, [item.as_dict() for item in compiled.diagnostics]
    assert compiled.yaml == (FIXTURES / f"{plan}.project.yaml").read_bytes()


@pytest.mark.parametrize("plan", PLANS)
def test_expected_project_validates_and_schedules_identically(plan):
    compiled = compile_fixture(f"{plan}.chrona")
    expected = load_yaml_bytes((FIXTURES / f"{plan}.project.yaml").read_bytes())
    assert validate_project(expected) == []
    assert schedule_summary(compiled.project) == schedule_summary(expected)
    assert edges(compiled.project) == edges(expected)


@pytest.mark.parametrize("plan", PLANS)
def test_output_is_byte_stable_lf_utf8_without_bom(plan):
    first, second = compile_fixture(f"{plan}.chrona"), compile_fixture(f"{plan}.chrona")
    assert first.yaml == second.yaml
    assert b"\r" not in first.yaml and first.yaml.endswith(b"\n") and not first.yaml.startswith(b"\xef\xbb\xbf")
    assert first.yaml.startswith(b"# generated by chrona compile (terse 0.1); once edited, this file is the authority\n")
    first.yaml.decode("utf-8")


def test_the_minimal_starter_is_four_lines_and_the_sketch_compiles():
    assert len((FIXTURES / "minimal-starter.chrona").read_text(encoding="utf-8").splitlines()) == 4
    sketch = compile_fixture("issue-sketch.chrona")
    assert sketch.ok and len(sketch.project["objects"]) == 4 and len(sketch.project["relations"]) == 3


def test_a_utf8_bom_and_crlf_do_not_change_the_output():
    source = (FIXTURES / "groups.chrona").read_bytes()
    plain = compile_fixture("groups.chrona")
    from chrona.usecases.terse_compile import compile_plan
    assert compile_plan(b"\xef\xbb\xbf" + source.replace(b"\n", b"\r\n")).yaml == plain.yaml
    assert compile_plan(source.rstrip(b"\n")).yaml == plain.yaml  # a final newline is optional
