"""Generate the reviewed presentation-capability prior-art matrix."""
from __future__ import annotations

import argparse
from pathlib import Path

from chrona.presentation.scene.capabilities import capability_ceiling


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs/research/presentation/presentation-capability-prior-art.md"
SOURCES = (
    ("Chrona", "local capability registry"),
    ("Editorial Gantt", "https://github.com/cathrynlavery/diagram-design"),
    ("Mermaid", "https://mermaid.js.org/syntax/gantt.html"),
    ("Microsoft Project", "https://support.microsoft.com/en-us/project/format-the-bar-chart-of-a-gantt-chart-view"),
)


def render() -> str:
    lines = [
        "# Presentation capability prior-art matrix", "",
        "Generated by `tools/presentation_prior_art.py` from the typed #391 capability registry.",
        "External columns are curated review references, not runtime inputs or feature commitments.", "",
        "## Reference sources", "",
    ]
    lines.extend(f"- [{name}]({source})" if source.startswith("http") else f"- {name}: {source}" for name, source in SOURCES)
    lines.extend(("", "## Capability dispositions", "", "| Capability | Primitive family | Chrona disposition | Owner | Reason | Reference |", "| --- | --- | --- | --- | --- | --- |"))
    for item in capability_ceiling():
        lines.append(f"| `{item.identifier}` | {item.primitive_family} | {item.disposition.value} | {item.owner} | {item.reason} | {item.reference} |")
    lines.extend(("", "## Review rule", "", "Every new presentation capability must first add a typed ceiling row and then refresh this matrix against its named primary sources. `unknown` external behavior is recorded as unknown, never inferred as absence."))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        return 0 if args.output.is_file() and args.output.read_text(encoding="utf-8") == rendered else 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
