#!/usr/bin/env python3
"""Render read-only Markdown pages for the validated design gallery."""
from __future__ import annotations

import argparse
from collections import defaultdict
import difflib
from pathlib import Path
import tempfile
from typing import Any, Mapping

import yaml

from chrona.resources import safe_load
from tools.example_inventory import corpus, validate_design_gallery


def _load(path: Path) -> Mapping[str, Any]:
    value = safe_load(path.read_bytes())
    if not isinstance(value, Mapping):
        raise ValueError(f"E_DESIGN_GALLERY_FORMAT:{path}")
    return value


def _reference_diff(contexts: list[Mapping[str, Any]]) -> list[str]:
    keys = ("view", "theme", "colorScheme", "layout")
    result = []
    for key in keys:
        values = [str(context["body"][key]["id"]) for context in contexts]
        if len(set(values)) > 1:
            result.append(f"- `{key}`: " + " → ".join(f"`{value}`" for value in values))
    return result or ["- No presentation-reference difference (invalid gallery input)."]


def _single_resource_diff(root: Path, bases: list[Path], contexts: list[Mapping[str, Any]]) -> list[str]:
    keys = ("view", "theme", "colorScheme", "layout")
    changed = [key for key in keys if len({str(context["body"][key]["id"]) for context in contexts}) > 1]
    if len(changed) != 1 or len(contexts) != 2:
        return []
    key = changed[0]
    paths = [root / base / str(context["body"][key]["address"]) for base, context in zip(bases, contexts)]
    left = yaml.safe_dump(_load(paths[0]), sort_keys=True).splitlines(keepends=True)
    right = yaml.safe_dump(_load(paths[1]), sort_keys=True).splitlines(keepends=True)
    diff = list(difflib.unified_diff(left, right, fromfile=paths[0].name, tofile=paths[1].name))
    if not diff:
        return []
    return ["## Referenced-resource YAML diff", "", f"The pair changes only `{key}`.", "", "```diff", *[line.rstrip() for line in diff], "", ""]


def render(root: Path) -> dict[Path, str]:
    catalogue_path = root / "docs/gallery/example-gallery.yaml"
    entries = corpus(root)
    validate_design_gallery(catalogue_path, root, entries)
    catalogue = _load(catalogue_path)
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for entry in catalogue["entries"]:
        grouped[entry["comparison"]["set"]].append(entry)
    pages: dict[Path, str] = {}
    index = ["# Public Design Gallery", "", "Generated by `tools/render_design_gallery.py --root .` from declared corpus evidence; it is not a renderer or an authoring input.",
             "", "## Comparison sets", "", "| Question | Dimension | Peers |", "| --- | --- | --- |"]
    for set_id, set_entries in sorted(grouped.items()):
        comparison = set_entries[0]["comparison"]
        page = Path("docs/gallery/sets") / f"{set_id}.md"
        index.append(f"| [{comparison['axis']}](sets/{page.name}) | `{comparison['dimension']}` | {len(set_entries)} |")
        bases = [Path(entries[(entry["corpus"], entry["slide"])]["manifest"]).parent for entry in set_entries]
        contexts = [_load(root / base / entries[(entry["corpus"], entry["slide"])]["context"])
                    for base, entry in zip(bases, set_entries)]
        supports = comparison.get("supports", [])
        support_note = f" Coupled support: {', '.join(f'`{item}`' for item in supports)}." if supports else ""
        lines = [f"# {comparison['axis']}", "", "Generated by `tools/render_design_gallery.py --root .`.", "", f"Design Space dimension: `{comparison['dimension']}`.{support_note}",
                 "", "## Peers", ""]
        for entry in set_entries:
            source = entries[(entry["corpus"], entry["slide"])]
            base = Path(source["manifest"]).parent
            image = Path("../../../") / base / source["expectedSvg"]
            context = Path("../../../") / base / source["context"]
            lines.extend([f"### {entry['narrative']['title']}", "", entry["narrative"]["purpose"], "",
                          f"![{entry['narrative']['title']}]({image.as_posix()})", "",
                          f"Corpus: `{entry['corpus']}` · slide: `{entry['slide']}` · [Context]({context.as_posix()})", ""])
        lines.extend(["## Presentation-reference diff", "", *_reference_diff(contexts), "",
                      *_single_resource_diff(root, bases, contexts),
                      "## Accessibility", ""])
        lines.extend(f"- {entry['narrative']['title']}: {entry['accessibility']['note']}" for entry in set_entries)
        lines.append("")
        pages[page] = "\n".join(lines)
    coverage = root / "docs/examples/corpus-coverage.md"
    index.extend(["", "## Semantic corpus coverage", "", f"See [semantic corpus coverage](../examples/{coverage.name}). It is one curation input, not presentation-vocabulary coverage or a render gate.", ""])
    deferred = catalogue.get("deferred", [])
    if deferred:
        index.extend(["## Deferred sets", "", "| Set | Dimension | Blocker |", "| --- | --- | --- |"])
        index.extend(f"| `{item['id']}` | `{item.get('dimension', 'outside Design Space')}` | {item['blocker']} |" for item in deferred)
        index.append("")
    pages[Path("docs/gallery/README.md")] = "\n".join(index)
    return pages


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(); root = args.root.resolve()
    pages = render(root)
    stale = [path for path, content in pages.items() if not (root / path).is_file() or (root / path).read_text(encoding="utf-8") != content]
    if args.check:
        if stale: raise SystemExit("E_DESIGN_GALLERY_STALE")
        return
    for path, content in pages.items(): _write(root / path, content)


if __name__ == "__main__":
    main()
