#!/usr/bin/env python3
"""Generate current semantic-state to completed-Scene-role evidence."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import tempfile
from typing import Any, Mapping

from chrona.presentation.model.semantic_realization import RealizationFamily, realization_families, validate_realization_families
from tools.derived_artifact_report import report_stale_artifact
from tools.presentation_coverage import Slide, discover


class SemanticRealizationCoverageError(ValueError):
    """The committed corpus cannot supply deterministic realization evidence."""


def _view(slide: Slide) -> Mapping[str, Any]:
    return next(document for kind, _path, document in slide.resources if kind == "view")


def _primitives(slide: Slide) -> tuple[Mapping[str, Any], ...]:
    try:
        document = json.loads(slide.scene.read_text(encoding="utf-8"))
        return tuple(primitive for surface in document["surfaces"] for primitive in surface["primitives"]
                     if isinstance(primitive, Mapping))
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        raise SemanticRealizationCoverageError(f"E_PRESENTATION_REALIZATION_SCENE:{slide.scene}") from error


def _table_columns(view: Mapping[str, Any], facet: str) -> frozenset[str]:
    body = view.get("body", {})
    columns = body.get("tableColumns", ()) if isinstance(body, Mapping) else ()
    return frozenset(str(column.get("id")) for column in columns
                     if isinstance(column, Mapping)
                     and isinstance(column.get("source"), Mapping)
                     and (column["source"].get("comparisonFacet") == facet
                          or column["source"].get("facet") == facet)
                     and isinstance(column.get("id"), str))


def _annotation_ids(view: Mapping[str, Any]) -> tuple[tuple[str, str], ...]:
    body = view.get("body", {})
    annotations = body.get("annotations", ()) if isinstance(body, Mapping) else ()
    return tuple((str(annotation.get("id")), str(annotation.get("purpose")))
                 for annotation in annotations if isinstance(annotation, Mapping)
                 and isinstance(annotation.get("id"), str) and isinstance(annotation.get("purpose"), str))


def _evidence(family: RealizationFamily, slides: tuple[Slide, ...]) -> tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]:
    states: set[str] = set()
    roles: set[str] = set()
    evidence: set[str] = set()
    for slide in slides:
        view, primitives = _view(slide), _primitives(slide)
        if family.selector.startswith("table-column:comparisonFacet="):
            columns = _table_columns(view, family.selector.rsplit("=", 1)[1])
            if not columns:
                continue
            states.update(family.admitted_states)
            roles.update(str(item.get("visualRole")) for item in primitives
                         if item.get("purpose") == family.primitive_purpose
                         and item.get("tableColumnId") in columns and isinstance(item.get("visualRole"), str))
        elif family.selector == "annotation:purpose":
            annotations = _annotation_ids(view)
            ids = {identifier for identifier, purpose in annotations if purpose in family.admitted_states}
            if not ids:
                continue
            states.update(purpose for identifier, purpose in annotations if identifier in ids)
            roles.update(str(item.get("visualRole")) for item in primitives
                         if item.get("sourceRef") in ids and item.get("purpose") == family.primitive_purpose
                         and isinstance(item.get("visualRole"), str))
        else:
            raise SemanticRealizationCoverageError(f"E_PRESENTATION_REALIZATION_SELECTOR:{family.selector}")
        evidence.add(slide.identifier)
    return tuple(sorted(states)), tuple(sorted(roles)), tuple(sorted(evidence))


def render(root: Path) -> str:
    """Render a deterministic registry/View/Scene report; never read adapters."""
    families = realization_families()
    validate_realization_families(families)
    slides = discover(root)
    rows = []
    for family in families:
        states, roles, evidence_slides = _evidence(family, slides)
        intentional = {state for state, _reason in family.intentional_equivalences}
        required = set(states) - intentional
        disposition = "not-selected" if not states else ("gap" if len(roles) < len(required) else "realized")
        reasons = "; ".join(f"{state}: {reason}" for state, reason in family.intentional_equivalences) or "—"
        rows.append((family, states, roles, evidence_slides, disposition, reasons))
    lines = ["# Semantic realization coverage", "", "Generated by `tools/semantic_realization_coverage.py` from the finite realization registry, View declarations, and committed inspection Scenes. It does not read SVG, PNG, or an adapter.", "",
             "## Current realization evidence", "", "| Family | Declared states | Realized Scene roles | Corpus slides | Disposition | Intentional equivalences |", "| --- | --- | --- | --- | --- | --- |"]
    for family, states, roles, slides, disposition, reasons in rows:
        lines.append("| `" + family.family_id + "` | " + ", ".join("`" + state + "`" for state in states) + " | "
                     + (", ".join("`" + role + "`" for role in roles) or "—") + " | "
                     + (", ".join(slides) or "—") + " | **" + disposition + "** | " + reasons + " |")
    lines.extend(["", "A `gap` is an admitted, non-equivalent semantic state family whose committed Scene realizes fewer roles than it requires. The corpus fixture may not select every admitted state yet; this is a triage result, not a claim that every distinct model field demands distinct paint."])
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, default=Path("docs/gallery/semantic-realization-coverage.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(); root = args.root.resolve(); output = args.output if args.output.is_absolute() else root / args.output
    content = render(root)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            report_stale_artifact(output=output, generated=content, code="E_PRESENTATION_REALIZATION_COVERAGE_STALE",
                                  refresh_argv=("python", "tools/semantic_realization_coverage.py"), root=root)
            raise SystemExit("E_PRESENTATION_REALIZATION_COVERAGE_STALE")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", newline="\n", dir=output.parent, delete=False) as temporary:
        temporary.write(content); temporary_path = Path(temporary.name)
    temporary_path.replace(output)


if __name__ == "__main__":
    main()
