#!/usr/bin/env python3
"""Check that finite schema vocabularies do not exceed owner acceptance."""
from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import tempfile
from typing import Any, Mapping

import yaml

from chrona.resources import safe_load


POLICY_VERSION = "chrona/declared-vocabulary-policy/v0.1"
DISPOSITIONS = {"finite", "open-ended"}


class VocabularyInventoryError(ValueError):
    """A vocabulary policy cannot truthfully describe its schema boundary."""


@dataclass(frozen=True, order=True)
class VocabularyEntry:
    schema: str
    pointer: str
    owner: str
    disposition: str
    accepted: tuple[str, ...] = ()
    reason: str | None = None

    @property
    def identity(self) -> tuple[str, str]:
        return self.schema, self.pointer


def _mapping(value: Any, code: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise VocabularyInventoryError(code)
    return value


def load_policy(path: Path) -> tuple[VocabularyEntry, ...]:
    try:
        document = _mapping(safe_load(path.read_bytes()), "E_VOCABULARY_POLICY_DOCUMENT")
    except (OSError, yaml.YAMLError) as error:
        raise VocabularyInventoryError("E_VOCABULARY_POLICY_READ") from error
    if document.get("version") != POLICY_VERSION:
        raise VocabularyInventoryError("E_VOCABULARY_POLICY_VERSION")
    values = document.get("vocabularies")
    if not isinstance(values, list):
        raise VocabularyInventoryError("E_VOCABULARY_POLICY_ENTRIES")
    entries: list[VocabularyEntry] = []
    for value in values:
        item = _mapping(value, "E_VOCABULARY_POLICY_ENTRY")
        schema, pointer, owner, disposition = (item.get(key) for key in ("schema", "pointer", "owner", "disposition"))
        if not all(isinstance(item, str) and item for item in (schema, pointer, owner)) or not isinstance(disposition, str) or disposition not in DISPOSITIONS:
            raise VocabularyInventoryError("E_VOCABULARY_POLICY_ENTRY")
        accepted = item.get("accepted", ())
        reason = item.get("reason")
        if disposition == "finite":
            if not isinstance(accepted, list) or not accepted or not all(isinstance(item, str) for item in accepted) or reason is not None:
                raise VocabularyInventoryError("E_VOCABULARY_POLICY_FINITE")
        elif accepted or not isinstance(reason, str) or not reason.strip():
            raise VocabularyInventoryError("E_VOCABULARY_POLICY_OPEN")
        entries.append(VocabularyEntry(schema, pointer, owner, disposition, tuple(accepted), reason))
    if len({entry.identity for entry in entries}) != len(entries):
        raise VocabularyInventoryError("E_VOCABULARY_POLICY_DUPLICATE")
    return tuple(sorted(entries))


def _pointer(document: Mapping[str, Any], pointer: str) -> Mapping[str, Any]:
    if not pointer.startswith("/"):
        raise VocabularyInventoryError(f"E_VOCABULARY_POINTER:{pointer}")
    value: Any = document
    for part in pointer[1:].split("/"):
        key = part.replace("~1", "/").replace("~0", "~")
        if isinstance(value, Mapping) and key in value:
            value = value[key]
        elif isinstance(value, list) and key.isdigit() and int(key) < len(value):
            value = value[int(key)]
        else:
            raise VocabularyInventoryError(f"E_VOCABULARY_POINTER:{pointer}")
    return _mapping(value, f"E_VOCABULARY_POINTER:{pointer}")


def declared_values(root: Path, entry: VocabularyEntry) -> tuple[str, ...]:
    try:
        document = _mapping(safe_load((root / entry.schema).read_bytes()), "E_VOCABULARY_SCHEMA_DOCUMENT")
    except (OSError, yaml.YAMLError) as error:
        raise VocabularyInventoryError(f"E_VOCABULARY_SCHEMA_READ:{entry.schema}") from error
    node = _pointer(document, entry.pointer)
    if "const" in node:
        values = (node["const"],)
    else:
        values = node.get("enum")
    if not isinstance(values, (list, tuple)) or not values or not all(isinstance(value, str) for value in values):
        raise VocabularyInventoryError(f"E_VOCABULARY_DECLARATION:{entry.schema}:{entry.pointer}")
    return tuple(sorted(values))


def validate(root: Path, entries: tuple[VocabularyEntry, ...]) -> None:
    for entry in entries:
        declared = declared_values(root, entry)
        if entry.disposition == "finite" and not set(declared).issubset(entry.accepted):
            wider = ",".join(sorted(set(declared) - set(entry.accepted)))
            raise VocabularyInventoryError(f"E_VOCABULARY_DECLARATION_WIDER:{entry.schema}:{entry.pointer}:{wider}")


def render(root: Path, entries: tuple[VocabularyEntry, ...]) -> str:
    lines = [
        "# Declared vocabulary inventory",
        "",
        "Generated by `tools/vocabulary_inventory.py`; it compares named schema vocabularies with their owning product acceptance boundary.",
        "",
        "| Schema field | Declared | Owner | Accepted / open-ended disposition |",
        "| --- | --- | --- | --- |",
    ]
    for entry in entries:
        declared = ", ".join(f"`{value}`" for value in declared_values(root, entry))
        accepted = ", ".join(f"`{value}`" for value in entry.accepted) if entry.disposition == "finite" else f"open-ended: {entry.reason}"
        lines.append(f"| `{entry.schema}{entry.pointer}` | {declared} | `{entry.owner}` | {accepted} |")
    if not entries:
        lines.append("| _No fields registered._ | — | — | — |")
    lines.append("")
    return "\n".join(lines)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent, delete=False) as temporary:
        temporary.write(content)
        temporary_path = Path(temporary.name)
    temporary_path.replace(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--policy", type=Path, default=Path("conformance/declared-vocabulary-policy-v0.1.yaml"))
    parser.add_argument("--output", type=Path, default=Path("docs/diagnostics/vocabulary-inventory.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(); root = args.root.resolve()
    policy_path = args.policy if args.policy.is_absolute() else root / args.policy
    output = args.output if args.output.is_absolute() else root / args.output
    entries = load_policy(policy_path)
    content = render(root, entries)
    if args.check:
        validate(root, entries)
        if not output.is_file() or output.read_text(encoding="utf-8") != content:
            raise SystemExit("E_VOCABULARY_INVENTORY_STALE")
        return
    write(output, content)


if __name__ == "__main__":
    main()
