"""A small hand-written YAML emitter for compiled Projects (Spec 65 section 8).

Not `yaml.safe_dump`: the bytes must not move with a PyYAML release. The contract is exact:
`safe_load(emit_project(project))` equals `project` for every Project the compiler can produce. LF newlines,
no BOM, a final newline, fixed key order (the order of the mapping given), single-quoted dates.
"""
from __future__ import annotations

import re
from typing import Any

HEADER = "# generated by chrona compile (terse 0.1); once edited, this file is the authority"

_PLAIN = re.compile(r"[A-Za-z][A-Za-z0-9 _-]*", re.ASCII)
_AMOUNT = re.compile(r"-?(?:0|[1-9][0-9]*)(?:d|w|wd)", re.ASCII)  # 1wd, -2d: never a YAML number
_VERSION = re.compile(r"timeline/v[0-9]+\.[0-9]+", re.ASCII)  # the Project version, plain as in the corpus
# YAML 1.1 words that PyYAML resolves to a bool or None (plus y/n, quoted for safety); also the safe_load key hazard.
_SPECIAL = frozenset({"y", "n", "yes", "no", "true", "false", "on", "off", "null"})
# Characters PyYAML accepts in a stream, other than line breaks it would fold inside a quoted scalar.
_PRINTABLE = re.compile("[\x20-\x7e\xa0-\ud7ff\ue000-\ufffd\U00010000-\U0010ffff]*")
_FOLDED = "\x85\u2028\u2029"  # line breaks PyYAML would fold inside a quoted scalar


def _scalar(value: Any) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, int):
        return str(value)
    if not isinstance(value, str):
        raise TypeError(f"cannot emit {type(value).__name__}")
    if _PLAIN.fullmatch(value) and not value.endswith(" ") and value.lower() not in _SPECIAL:
        return value
    if _AMOUNT.fullmatch(value) or _VERSION.fullmatch(value):
        return value
    if _PRINTABLE.fullmatch(value) and not any(char in _FOLDED for char in value):
        return "'" + value.replace("'", "''") + "'"
    out = ['"']
    for char in value:
        code = ord(char)
        if char in '"\\':
            out.append("\\" + char)
        elif _PRINTABLE.fullmatch(char) and char not in _FOLDED:
            out.append(char)
        elif code <= 0xFF:
            out.append(f"\\x{code:02X}")
        elif code <= 0xFFFF:
            out.append(f"\\u{code:04X}")
        else:
            out.append(f"\\U{code:08X}")
    out.append('"')
    return "".join(out)


def _flow(value: Any) -> str:
    if isinstance(value, dict):
        return "{" + ", ".join(f"{_scalar(key)}: {_flow(item)}" for key, item in value.items()) + "}"
    if isinstance(value, list):
        return "[" + ", ".join(_flow(item) for item in value) + "]"
    return _scalar(value)


def _is_flow(path: tuple[str, ...]) -> bool:
    """Only an object's schedule and a calendar's weekday list are one-line flow collections."""
    return len(path) == 3 and (path[0], path[2]) in {("objects", "schedule"), ("calendars", "working_days")}


def _block(value: dict[str, Any], path: tuple[str, ...], out: list[str]) -> None:
    pad = "  " * len(path)
    for key, item in value.items():
        label = _scalar(key)
        here = (*path, key)
        if isinstance(item, (dict, list)) and _is_flow(here):
            out.append(f"{pad}{label}: {_flow(item)}")
        elif isinstance(item, dict):
            out.append(f"{pad}{label}:")
            _block(item, here, out)
        elif isinstance(item, list):
            out.append(f"{pad}{label}:")
            for entry in item:
                out.append(f"{pad}  - {_flow(entry)}")
        else:
            out.append(f"{pad}{label}: {_scalar(item)}")


def emit_project(project: dict[str, Any]) -> str:
    """The deterministic YAML text of a compiled Project (LF only, final newline)."""
    lines = [HEADER]
    _block(project, (), lines)
    return "\n".join(lines) + "\n"
